### PR TITLE
feat: switch to offical express engine

### PR DESCRIPTION
**Pull request by theomathieubhvr**

### CODE REVIEW

**Comment by theomathieubhvr** [comment]
This switch is fully working 👍

**Comment by fulls1z3** [comment]
@theomathieubhvr thanks for your awesome contributions, I'll review it as soon as possible and then merge.

Great job 👍

**Comment by fulls1z3** [comment]
merged 👍

**Comment by jrmcdona** [comment]
I still get this error.  I just cloned today.  Yarn install throw s an error.  See below,

C:\src\universal>yarn install
yarn install v0.24.6
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
error @nguniversal/express-engine@1.0.0-beta.2: The engine "node" is incompatible with this module. Expected version ">= 5.4.1 <= 7".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

C:\src\universal>node -v v8.1.2

**Comment by theomathieubhvr** [comment]
Yes universal is still incompatible with node 8. You have to use nodejs 6. A pull request has been merged not long ago so support should be coming soon.

**Comment by theomathieubhvr** [comment]
See https://github.com/angular/universal/pull/758#event-1184644755

**Comment by fulls1z3** [comment]
Well, it seems like guys in `angular` will not update the repository soon, and we can't afford their (*late*) releases. We're going to roll back to our own express-engine, where we have full control to run node.js 8.x.

**Pull request merged**
