### PR TITLE
feat: update `ngtools` to 1.5.5

### PR DESCRIPTION
**Pull request by theomathieubhvr**

### CODE REVIEW

**Comment by fulls1z3** [comment]
@theomathieubhvr I just saw the notification, but we should be very careful merging this. There's an issue about `@ngtools/webpack` which breaks down the whole compilation process.

Better wait for news from my side, ensuring the project compiles without a problem.

**Comment by theomathieubhvr** [comment]
Sure I just tested this based on this comment : https://github.com/angular/angular-cli/issues/7113#issuecomment-318699716

And travis is succeeding.

**Comment by theomathieubhvr** [comment]
I'll make more tests before merging it ;)

**Comment by fulls1z3** [comment]
@theomathieubhvr about tests, i have no doubts - and you're always making awesome contributions to this project 👍 

This weekend I think I have some free time (*which was not the case last 3 months, obviously from my decreasing amount of contributions*) and I'll test the same on 5+ different projects varying from v4.0.0-rc's to 5.0.0-beta.0. And then I'll let you know about this. If not, let's merge it on next Monday.

Sounds like a deal? Well, we can add a couple cups of coffee to make it a bet 😄

**Comment by theomathieubhvr** [comment]
It's a deal 👍

**Comment by fulls1z3** [comment]
@theomathieubhvr I've tested it on the projects, all failed with `No NgModule metadata found for 'AppModule'.` error.

**Comment by fulls1z3** [comment]
Well, solved this issue on #43, #39, #29 as well as sharing some info on https://github.com/angular/angular-cli/issues/6833.

Merging this!

**Pull request merged**
