### PR TITLE
fix: app flickering

### PR DESCRIPTION
**Pull request by theomathieubhvr**

### CODE REVIEW

**Comment by theomathieubhvr** [comment]
See #15

**Comment by fulls1z3** [comment]
@theomathieubhvr thanks for this PR, it's one of the suggested approaches - but as far as I remember `initialNavigation` has some side effects. I'll test this PR on multiple projects based on this seed and then provide some feedback.

**Comment by theomathieubhvr** [comment]
Ok i did not know. I'll check too on our production websites.

Thanks !

**Comment by dr1ss** [comment]
I tryed it on one of my apps, the meta data (title, description etc..) do not get translated.

**Pull request closed without merging**
